language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
    - REQ='django>=1.11,<2.0 django-filer==1.4.2'
    - REQ='django>=2.0,<2.1 django-filer==1.4.2'
    # - REQ='django>=2.1,<2.2 FILER="django-filer==1.4.2'

matrix:
  allow-failures:
  exclude:
    - python: '2.7'
      env: REQ='django>=2.0,<2.1 django-filer==1.4.2'
    - python: '2.7'
      env: REQ='django>=2.1,<2.2 django-filer==1.4.2'

# command to install dependencies
install:
  - pip install .
  - pip install $REQ
  - pip install -r test_requirements.txt

# command to run tests
script: python manage.py test
